### ISSUE TITLE
Shortcodes

### ISSUE THREAD

**Issue by llamadillo** [CouchCMS/Documentation#12]

**Comment by kksidd** [comment]
The closing PHP tag is optional (in fact, it is a recommended practice to leave it out) so that is not a problem.

That said, I tested the sample kfunctions.php available as a download on that page and also tested creating a new kfunctions,php file and copy/pasting the sample code in that. 

I couldn't duplicate the error you reported in either case.

Perhaps the issue you mentioned has a different cause?
